require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Max: 120

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: double_quotes

# rubocop-rspec

RSpec/MultipleExpectations:
  Max: 15

RSpec/ExampleLength:
  Max: 15
