Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 120

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/IfUnlessModifier:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
