#!/usr/bin/env ruby

lib = File.expand_path('../../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'gistory'

# do i need the repo here???
Gistory::Cli.new(repo: Gistory::GitRepo.new(dir: '.'), args: ARGV).run
